project_id = "fjgdcmtwstmslmbxlsga"

[functions.chat]
verify_jwt = false

[functions.ai-action]
verify_jwt = false

[functions.admin-invite]
verify_jwt = true

[functions.socio-tools]
verify_jwt = false

[functions.verify-certificate]
verify_jwt = false
