// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/tools/list-companies.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function resolveContractScope(supabase, companyId, contractId) {
  if (!contractId) return { contractId: null, contract: null };
  const { data, error } = await supabase.from("contracts").select("id, company_id, status, journey_stage, current_cycle, product_id, product_version_id").eq("id", contractId).eq("company_id", companyId).maybeSingle();
  if (error) throw new Error(error.message);
  if (!data) throw new Error("Contrata\xE7\xE3o n\xE3o encontrada ou sem acesso para esta empresa.");
  return { contractId: data.id, contract: data };
}
function applyContractScope(query, contractId) {
  return contractId ? query.eq("contract_id", contractId) : query.is("contract_id", null);
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "N\xE3o autenticado. Conecte-se ao MENTOR 4X novamente." }],
    isError: true
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}

// src/lib/mcp/tools/list-companies.ts
var list_companies_default = defineTool({
  name: "list_companies",
  title: "Listar empresas",
  description: "Lista as empresas que o usu\xE1rio conectado pode acessar no Mentor 4X, com o ciclo atual da Jornada SEE_4X, n\xEDvel de Improviso e score geral.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("companies").select("id, name, segment, journey_stage, chaos_level, overall_score, owner_dependency, projected_revenue, started_at, contracts(id, status, journey_stage, current_cycle, product_id, product_version_id)").order("name");
    if (error) return errorResult(error.message);
    return jsonResult({ companies: data ?? [] });
  }
});

// src/lib/mcp/tools/get-company-overview.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z } from "npm:zod@^3.25.76";
var get_company_overview_default = defineTool2({
  name: "get_company_overview",
  title: "Diagn\xF3stico da empresa",
  description: "Retorna o panorama de uma empresa: dados gerais, \xFAltimos scores por pilar, metas em aberto, gargalos n\xE3o resolvidos e tarefas pendentes.",
  inputSchema: {
    company_id: z.string().describe("UUID da empresa (use list_companies para descobrir)."),
    contract_id: z.string().optional().describe("UUID da contrata\xE7\xE3o/ciclo ativo, quando a empresa tiver mais de uma contrata\xE7\xE3o.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ company_id, contract_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let scope;
    try {
      scope = await resolveContractScope(supabase, company_id, contract_id);
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
    const [company, scores, goals, bottlenecks, tasks] = await Promise.all([
      supabase.from("companies").select("*").eq("id", company_id).maybeSingle(),
      applyContractScope(supabase.from("pillar_scores").select("pillar, score, measured_at, blind_spots, recommendations").eq("company_id", company_id).order("measured_at", { ascending: false }), scope.contractId).limit(30),
      applyContractScope(supabase.from("goals").select("id, title, status, pillar, due_date, financial_impact").eq("company_id", company_id).neq("status", "concluido").order("due_date", { ascending: true }), scope.contractId).limit(50),
      applyContractScope(supabase.from("bottlenecks").select("id, name, area, urgency, progress, estimated_value").eq("company_id", company_id).eq("resolved", false), scope.contractId).limit(50),
      applyContractScope(supabase.from("tasks").select("id, title, due_date, done").eq("company_id", company_id).eq("done", false), scope.contractId).limit(50)
    ]);
    const failure = [company, scores, goals, bottlenecks, tasks].find((r) => r.error);
    if (failure?.error) return errorResult(failure.error.message);
    if (!company.data) return errorResult("Empresa n\xE3o encontrada ou sem acesso.");
    return jsonResult({
      company: company.data,
      contract: scope.contract,
      pillar_scores: scores.data ?? [],
      open_goals: goals.data ?? [],
      open_bottlenecks: bottlenecks.data ?? [],
      pending_tasks: tasks.data ?? []
    });
  }
});

// src/lib/mcp/tools/list-goals.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z2 } from "npm:zod@^3.25.76";
var list_goals_default = defineTool3({
  name: "list_goals",
  title: "Listar metas",
  description: "Lista as metas (semanais/mensais) de uma empresa no MENTOR 4X. Opcionalmente filtra por status.",
  inputSchema: {
    company_id: z2.string().describe("UUID da empresa."),
    contract_id: z2.string().optional().describe("UUID da contrata\xE7\xE3o/ciclo ativo. Se omitido, lista apenas registros legados sem contrata\xE7\xE3o."),
    status: z2.enum(["nao_iniciado", "em_andamento", "concluido", "atrasado", "bloqueado"]).optional().describe("Filtro opcional por status da meta.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ company_id, contract_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let scope;
    try {
      scope = await resolveContractScope(supabase, company_id, contract_id);
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
    let query = supabase.from("goals").select("id, title, description, status, pillar, indicator, due_date, week_start, financial_impact, mentor_comment, evidence_url").eq("company_id", company_id).order("due_date", { ascending: true }).limit(200);
    query = applyContractScope(query, scope.contractId);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ goals: data ?? [] });
  }
});

// src/lib/mcp/tools/create-goal.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z3 } from "npm:zod@^3.25.76";
var create_goal_default = defineTool4({
  name: "create_goal",
  title: "Criar meta",
  description: "Cria uma nova meta de execu\xE7\xE3o para uma empresa do MENTOR 4X. Use ap\xF3s confirmar a empresa correta com list_companies.",
  inputSchema: {
    company_id: z3.string().describe("UUID da empresa."),
    contract_id: z3.string().optional().describe("UUID da contrata\xE7\xE3o/ciclo ativo. Se omitido, cria registro legado sem contrata\xE7\xE3o."),
    title: z3.string().describe("T\xEDtulo da meta, objetivo e mensur\xE1vel."),
    description: z3.string().optional().describe("Detalhes do plano de execu\xE7\xE3o."),
    pillar: z3.enum(["crescimento", "eficiencia", "encantamento", "lideranca"]).optional().describe("Pilar 4X relacionado, se aplic\xE1vel."),
    indicator: z3.string().optional().describe("Indicador de sucesso (KPI)."),
    due_date: z3.string().optional().describe("Prazo no formato YYYY-MM-DD."),
    financial_impact: z3.number().optional().describe("Impacto financeiro estimado em BRL.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let scope;
    try {
      scope = await resolveContractScope(supabase, input.company_id, input.contract_id);
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
    const { data, error } = await supabase.from("goals").insert({
      company_id: input.company_id,
      contract_id: scope.contractId,
      title: input.title.trim(),
      description: input.description ?? null,
      pillar: input.pillar ?? null,
      indicator: input.indicator ?? null,
      due_date: input.due_date ?? null,
      financial_impact: input.financial_impact ?? null,
      status: "nao_iniciado",
      created_by: ctx.getUserId()
    }).select().maybeSingle();
    if (error) return errorResult(error.message);
    return jsonResult({ goal: data });
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z4 } from "npm:zod@^3.25.76";
var list_tasks_default = defineTool5({
  name: "list_tasks",
  title: "Listar plano de a\xE7\xE3o",
  description: "Lista as tarefas do plano de a\xE7\xE3o de uma empresa. Por padr\xE3o s\xF3 as pendentes.",
  inputSchema: {
    company_id: z4.string().describe("UUID da empresa."),
    contract_id: z4.string().optional().describe("UUID da contrata\xE7\xE3o/ciclo ativo. Se omitido, lista apenas registros legados sem contrata\xE7\xE3o."),
    include_done: z4.boolean().optional().describe("Se true, inclui tamb\xE9m tarefas conclu\xEDdas.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ company_id, contract_id, include_done }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let scope;
    try {
      scope = await resolveContractScope(supabase, company_id, contract_id);
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
    let query = supabase.from("tasks").select("id, title, description, due_date, done, created_at").eq("company_id", company_id).order("due_date", { ascending: true }).limit(200);
    query = applyContractScope(query, scope.contractId);
    if (!include_done) query = query.eq("done", false);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ tasks: data ?? [] });
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z5 } from "npm:zod@^3.25.76";
var create_task_default = defineTool6({
  name: "create_task",
  title: "Criar tarefa",
  description: "Adiciona uma tarefa ao plano de a\xE7\xE3o de uma empresa do MENTOR 4X.",
  inputSchema: {
    company_id: z5.string().describe("UUID da empresa."),
    contract_id: z5.string().optional().describe("UUID da contrata\xE7\xE3o/ciclo ativo. Se omitido, cria registro legado sem contrata\xE7\xE3o."),
    title: z5.string().describe("T\xEDtulo curto e acion\xE1vel da tarefa."),
    description: z5.string().optional().describe("Detalhes da execu\xE7\xE3o."),
    due_date: z5.string().optional().describe("Prazo no formato YYYY-MM-DD.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ company_id, contract_id, title, description, due_date }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let scope;
    try {
      scope = await resolveContractScope(supabase, company_id, contract_id);
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
    const { data, error } = await supabase.from("tasks").insert({
      company_id,
      contract_id: scope.contractId,
      title: title.trim(),
      description: description ?? null,
      due_date: due_date ?? null,
      done: false
    }).select().maybeSingle();
    if (error) return errorResult(error.message);
    return jsonResult({ task: data });
  }
});

// src/lib/mcp/tools/list-bottlenecks.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z6 } from "npm:zod@^3.25.76";
var list_bottlenecks_default = defineTool7({
  name: "list_bottlenecks",
  title: "Listar gargalos",
  description: "Lista os gargalos (bottlenecks) mapeados de uma empresa, com urg\xEAncia, progresso da corre\xE7\xE3o e valor estimado.",
  inputSchema: {
    company_id: z6.string().describe("UUID da empresa."),
    contract_id: z6.string().optional().describe("UUID da contrata\xE7\xE3o/ciclo ativo. Se omitido, lista apenas registros legados sem contrata\xE7\xE3o."),
    include_resolved: z6.boolean().optional().describe("Se true, inclui gargalos j\xE1 resolvidos.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ company_id, contract_id, include_resolved }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let scope;
    try {
      scope = await resolveContractScope(supabase, company_id, contract_id);
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
    let query = supabase.from("bottlenecks").select("id, name, area, impact, urgency, progress, estimated_value, correction_plan, resolved").eq("company_id", company_id).order("urgency", { ascending: false }).limit(200);
    query = applyContractScope(query, scope.contractId);
    if (!include_resolved) query = query.eq("resolved", false);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ bottlenecks: data ?? [] });
  }
});

// src/lib/mcp/tools/create-bottleneck.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z7 } from "npm:zod@^3.25.76";
var create_bottleneck_default = defineTool8({
  name: "create_bottleneck",
  title: "Registrar gargalo",
  description: "Registra um novo gargalo operacional de uma empresa do MENTOR 4X, com urg\xEAncia e plano de corre\xE7\xE3o.",
  inputSchema: {
    company_id: z7.string().describe("UUID da empresa."),
    contract_id: z7.string().optional().describe("UUID da contrata\xE7\xE3o/ciclo ativo. Se omitido, cria registro legado sem contrata\xE7\xE3o."),
    name: z7.string().describe("Nome do gargalo."),
    area: z7.string().optional().describe("\xC1rea da empresa afetada (ex.: comercial, financeiro)."),
    impact: z7.string().optional().describe("Descri\xE7\xE3o do impacto no neg\xF3cio."),
    urgency: z7.enum(["baixa", "media", "alta", "critica"]).optional().describe("Urg\xEAncia do gargalo. Padr\xE3o: media."),
    correction_plan: z7.string().optional().describe("Plano de corre\xE7\xE3o proposto."),
    estimated_value: z7.number().optional().describe("Valor estimado em BRL travado por este gargalo.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let scope;
    try {
      scope = await resolveContractScope(supabase, input.company_id, input.contract_id);
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
    const { data, error } = await supabase.from("bottlenecks").insert({
      company_id: input.company_id,
      contract_id: scope.contractId,
      name: input.name.trim(),
      area: input.area ?? null,
      impact: input.impact ?? null,
      urgency: input.urgency ?? "media",
      correction_plan: input.correction_plan ?? null,
      estimated_value: input.estimated_value ?? null,
      progress: 0,
      resolved: false
    }).select().maybeSingle();
    if (error) return errorResult(error.message);
    return jsonResult({ bottleneck: data });
  }
});

// src/lib/mcp/tools/record-pillar-score.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z8 } from "npm:zod@^3.25.76";
var record_pillar_score_default = defineTool9({
  name: "record_pillar_score",
  title: "Registrar score de pilar",
  description: "Registra uma nova nota (0 a 100) para um pilar do m\xE9todo 4X de uma empresa, com pontos cegos e recomenda\xE7\xF5es. Requer permiss\xE3o de mentor/estrategista.",
  inputSchema: {
    company_id: z8.string().describe("UUID da empresa."),
    contract_id: z8.string().optional().describe("UUID da contrata\xE7\xE3o/ciclo ativo. Se omitido, cria registro legado sem contrata\xE7\xE3o."),
    pillar: z8.enum(["crescimento", "eficiencia", "encantamento", "lideranca"]).describe("Pilar do m\xE9todo 4X."),
    score: z8.number().describe("Nota de 0 a 100."),
    blind_spots: z8.string().optional().describe("Pontos cegos identificados."),
    recommendations: z8.string().optional().describe("Recomenda\xE7\xF5es de a\xE7\xE3o.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const score = Math.max(0, Math.min(100, Math.round(input.score)));
    const supabase = supabaseForUser(ctx);
    let scope;
    try {
      scope = await resolveContractScope(supabase, input.company_id, input.contract_id);
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
    const { data, error } = await supabase.from("pillar_scores").insert({
      company_id: input.company_id,
      contract_id: scope.contractId,
      pillar: input.pillar,
      score,
      blind_spots: input.blind_spots ?? null,
      recommendations: input.recommendations ?? null
    }).select().maybeSingle();
    if (error) return errorResult(error.message);
    return jsonResult({ pillar_score: data });
  }
});

// src/lib/mcp/index.ts
var projectRef = "fjgdcmtwstmslmbxlsga";
var mcp_default = defineMcp({
  name: "mentor-4x",
  title: "Mentor 4X",
  version: "0.1.0",
  instructions: "Ferramentas do Mentor 4X, plataforma do SEE_4X (Sistema de Estrutura\xE7\xE3o Empresarial 4X, RC360). Use `list_companies` primeiro para descobrir as empresas acess\xEDveis e seus UUIDs, e `get_company_overview` para um diagn\xF3stico completo (scores por pilar, metas, gargalos e tarefas). As demais ferramentas leem e criam metas, tarefas do plano de a\xE7\xE3o, gargalos e scores de pilar. Todas as opera\xE7\xF5es respeitam as permiss\xF5es do usu\xE1rio conectado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_companies_default,
    get_company_overview_default,
    list_goals_default,
    create_goal_default,
    list_tasks_default,
    create_task_default,
    list_bottlenecks_default,
    create_bottleneck_default,
    record_pillar_score_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.3/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
